services:
  typesense:
    image: typesense/typesense:27.1
    ports:
      - ${FORWARD_TYPESENSE_PORT:-8108}:8108
    environment:
      TYPESENSE_DATA_DIR: ${TYPESENSE_DATA_DIR:-/typesense-data}
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY:-xyz}
      TYPESENSE_ENABLE_CORS: ${TYPESENSE_ENABLE_CORS:-true}
    volumes:
      - sail-typesense:/typesense-data
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--spider'
        - 'http://localhost:8108/health'
      retries: 5
      timeout: 7s

  soketi:
    image: quay.io/soketi/soketi:latest-16-alpine
    environment:
      SOKETI_DEBUG: ${SOKETI_DEBUG:-1}
      SOKETI_METRICS_SERVER_PORT: 9601
      SOKETI_DEFAULT_APP_ID: ${PUSHER_APP_ID}
      SOKETI_DEFAULT_APP_KEY: ${PUSHER_APP_KEY}
      SOKETI_DEFAULT_APP_SECRET: ${PUSHER_APP_SECRET}
    ports:
      - ${PUSHER_PORT:-6001}:6001
      - ${PUSHER_METRICS_PORT:-9601}:9601

volumes:
  sail-typesense:
    driver: local
